language: erlang
otp_release:
- 18.1
- 18.0
notifications:
  slack:
    secure: IOBwgjVyFZMRsWnIbRxb2DMT5rQbhP+ZDVyH7o8hEvj1eFbGEWAOgUJBa5lNKta5IiVc5HDmMvVhBLqxxG1MeIcZvm53qdaLb0ErPJyjOYO+ZyokR6tbF1ToayewVzUQ58V9wPJIpDv/wGQ6GEqgy0g5V5XIxlmmZZr/mpDI11H8LyNSWqE3T8rdM6XHmPjeRpaCZYM79wl9Gn3NWaG46YSETZJYF1Q8jHacnyeP7DRFsyMjx6YRsSdWZs7ytH0nI4lO2Kokzu3OooIjYHm6+nfo9Uqc0kdV9fD5G5CLYXIZwnU26mO80spnb4YxnJExUYVhT+2GwHvSQ73KK052sEol/j8s5I3uxn7sv8jh/ZQXGkPo2iyEn0Ym23Yv+jcQDtisvMnEWZLlRitGbNSaWzYWzDY4U7oIcLk7qhN64CHYOgK1tY/KRfaK7EnBAlomA1SuF3inNN7gChyRzheyUE5zrruhC3jey7bx2fUZDPnXkDSfFGVCLi21hnTttIEk4grZdRXQ2kgNpCo0PSbjQrcCeI1n2j9ZfZRzdssmjGqT6ppuLlxktyHr4Yi3HwXQVa0bwT6gn7qiwG6Gf7EiIJy+Pm12nQhHqPyNifyQ62UoKOFbMVz7ecNElUJia+CIzBfn/c/QoesJu2QZqi8Lk2O5LrbsJmUdKzze5F77eM8=
